checks:
  go: true
filter:
  excluded_paths:
    - "*_test.go"
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      environment:
        go:
          version: go1.8.3
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
    tests:
      environment:
        go:
          version: go1.8.3
#    coverage:
#      tests:
#        override:
#          - command: go test -coverprofile=cover.out
#            coverage:
#              file: 'cover.out'
#              format: 'go-cc'
